### PR TITLE
Readme Translation (Spanish) 

### PR DESCRIPTION
**Pull request by another-sapiens**
Hi!
Just wanted to say this app is amazing, specially the UI. Was thinking of how to contribute, and I did so in the only way I know: Translations. 

I'm sure the Spanish-speaking community will love your app.

### CODE REVIEW

**Comment by vishnuraghavb** [comment]
Hello 👋🏽 
Thank you so much for the kind words!
It is very kind of you that you've took your time to contribute as much you can for EnRecipes.
To my surprise, I've been thinking recently to translate the fastlane metadata info on Weblate. I'll set it up soon for others to contribute as well! Thanks again for initiating this process. 😊

**Comment by vishnuraghavb** [comment]
Hi @another-sapiens Please be informed that I've successfully linked metadata translations with Weblate. Here after you could help us translate the files at the URL: https://hosted.weblate.org/projects/enrecipes/store-listing/

**Comment by another-sapiens** [comment]
Sounds great! Also, just noticed the features Roadmap and now I'm super hyped. 

Keep up the great work, stay awesome!

**Comment by another-sapiens** [comment]
Didn't see that last message, I'll see what I can do.

**Comment by another-sapiens** [comment]
I'm having some trouble, upon submitting a suggestion for the translations, it says the text is too long. I've tried removing parts of the formatting to no avail.
It would be a good idea to make the word limit longer for less compact languages, like Spanish.

Other than that, I've managed to translate most of the changelogs, which was the only part missing.

**Comment by vishnuraghavb** [comment]
I'm currently trying to fix the exact same issue 😄 on Weblate. I'll let you know in sometime. Even I've lost some of my Tamil language translations because of this.

**Comment by vishnuraghavb** [comment]
Found it!
It actually gets the max-length from Google PlayStore's guidelines. They limit the max-length of changelogs to 500 characters. But here I've 600+ characters on my latest release's changelog. This causes an issue. So for now all we can do is skip some strings or lines in the changelog. I'll make it work from my future releases.

**Comment by another-sapiens** [comment]
Ohh, I see! 
Maybe I could just ignore a few non-vital lines for the time being, ignore part of the formatting to shave off a few signs and whatnot.

Thank you for putting so much effort into this, too!

**Comment by another-sapiens** [comment]
Changelogs translated. 😎

**Comment by vishnuraghavb** [comment]
I've fixed the character length issue on changelog 7. Please have a look at it.

**Comment by another-sapiens** [comment]
Much better! I've made new suggestions based on your changes.
Anyhow, I didn't list the new languages as the people who will find it important won't be using Spanish.

**Comment by vishnuraghavb** [comment]
That's fine! Thanks for your time.
I'll make it better from the next time 😉

**Comment by another-sapiens** [comment]
Awesome! Thank you, too.

**Pull request merged**
